// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSzpzH0c6md45Sw6aF-njMmQbUAbcizR8',
    appId: '1:330273754774:web:f8e7d449a20ebb65013cb7',
    messagingSenderId: '330273754774',
    projectId: 'my-project-2002-1403f',
    authDomain: 'my-project-2002-1403f.firebaseapp.com',
    storageBucket: 'my-project-2002-1403f.firebasestorage.app',
    measurementId: 'G-CEHJKPYFL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQDIEbWMO4cOC630nUQ-V6Wx6K5MdMkx0',
    appId: '1:330273754774:android:5ab90a829dde741f013cb7',
    messagingSenderId: '330273754774',
    projectId: 'my-project-2002-1403f',
    storageBucket: 'my-project-2002-1403f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4mJceGC6_Vg4_szkxbKmzhrcc2IMmeGY',
    appId: '1:330273754774:ios:2cda5e60c685dfab013cb7',
    messagingSenderId: '330273754774',
    projectId: 'my-project-2002-1403f',
    storageBucket: 'my-project-2002-1403f.firebasestorage.app',
    iosBundleId: 'com.example.clinicManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4mJceGC6_Vg4_szkxbKmzhrcc2IMmeGY',
    appId: '1:330273754774:ios:2cda5e60c685dfab013cb7',
    messagingSenderId: '330273754774',
    projectId: 'my-project-2002-1403f',
    storageBucket: 'my-project-2002-1403f.firebasestorage.app',
    iosBundleId: 'com.example.clinicManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSzpzH0c6md45Sw6aF-njMmQbUAbcizR8',
    appId: '1:330273754774:web:d12010d2316f89ed013cb7',
    messagingSenderId: '330273754774',
    projectId: 'my-project-2002-1403f',
    authDomain: 'my-project-2002-1403f.firebaseapp.com',
    storageBucket: 'my-project-2002-1403f.firebasestorage.app',
    measurementId: 'G-7VNTN887ZD',
  );
}
